<?php
// seed_all_20_countries.php - Full-Scale 2026 Seeder for All 39 Countries
error_reporting(E_ALL);
ini_set('display_errors', 1);

require_once 'includes/db.php';

echo "<pre>";
echo "=== SEEDING ALL 39 STUDY DESTINATIONS (2026 METRICS) ===\n";

$allCountriesData = [
    'australia' => [
        'travel_hours' => 'Approx 12-14 hours (Flight from India)',
        'study_options' => "Bachelor's, Master's, MBA, Doctoral (PhD), Diploma & Pathway Programs",
        'roi_advantage' => 'Indian Advantage: Exclusive 3-Year stay-back for Master’s graduates (AI-ECTA Benefit)',
        'roi_priority' => 'Priority Triage: Fast-track visa processing for Priority 1 Institutions',
        'roi_wage' => 'Minimum Wage: $24.95 AUD/hr (Among the highest student earnings globally)',
        'roi_qs' => 'QS Power: 6 Universities in the World’s Top 50',
        'living_cost_local' => '$29,710 AUD',
        'living_cost_inr' => '₹16.8 Lakhs',
        'visa_fee_local' => '$2,000 AUD',
        'visa_fee_inr' => '₹1.1 Lakhs',
        'weekly_budget_local' => '$450 – $650 AUD',
        'weekly_budget_inr' => 'Covers Rent, Food & Transit',
        'earnings_potential_local' => '$48,000+ AUD',
        'earnings_potential_inr' => 'Annual income if working maximum allowed hours',
        'stayback_bachelors' => '2 Years',
        'stayback_bachelors_stem' => '3 Years (STEM 1st Class)',
        'stayback_masters' => '3 Years (AI-ECTA)',
        'stayback_doctoral' => '4 Years',
        'stayback_regional' => '+1 Year (Up to 6 Years Total)',
        'upcoming_intakes' => "February 2027 (Major Intake) | Deadline: October 2026\nJuly 2026 / 2027 (Secondary Intake) | Deadline: March / May",
        'demand_careers' => "AI Engineers\nRenewable Energy Specialists\nRegistered Nurses\nCyber Security Experts",
        'features' => '["AI-ECTA 3-Yr Stay-back","Priority Triage Processing","High Minimum Wage ($24.95/hr)","6 Top 50 Universities"]'
    ],
    'usa' => [
        'travel_hours' => 'Approx 15-18 hours',
        'study_options' => "Bachelor's, Master's, MBA, STEM OPT, Doctoral (PhD)",
        'roi_advantage' => 'STEM OPT Extension: Up to 36 Months legal stay-back',
        'roi_priority' => 'Premium Processing: Fast-track I-20 and F-1 student visa processing',
        'roi_wage' => '$15.00 - $20.00 USD/hr (Varies by state & campus jobs)',
        'roi_qs' => 'Ivy League & Tier 1: Most universities in the World’s Top 100',
        'living_cost_local' => '$20,000 USD',
        'living_cost_inr' => '₹16.5 Lakhs',
        'visa_fee_local' => '$185 USD',
        'visa_fee_inr' => '₹15,000',
        'weekly_budget_local' => '$350 – $500 USD',
        'weekly_budget_inr' => 'Rent, utilities & meal plans',
        'earnings_potential_local' => '$35,000+ USD',
        'earnings_potential_inr' => 'Annual part-time & internship earnings potential',
        'stayback_bachelors' => '1 Year (OPT)',
        'stayback_bachelors_stem' => '3 Years (STEM OPT)',
        'stayback_masters' => '3 Years (STEM OPT)',
        'stayback_doctoral' => '3 Years',
        'stayback_regional' => 'CPT & OPT industry placements',
        'upcoming_intakes' => "Fall (August) | Deadline: Dec - Jan\nSpring (January) | Deadline: June - August",
        'demand_careers' => "Software Engineers\nData Scientists\nFinTech Specialists\nBiomedical Engineers",
        'features' => '["3-Year STEM OPT","Ivy League & Tier 1","High Internships Pay","Flexible Majors"]'
    ],
    'uk' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "1-Year Master's, Bachelor's, MBA, PhD",
        'roi_advantage' => 'Graduate Route: Guaranteed 2 Years stay-back for all grads',
        'roi_priority' => 'Shorter Duration: 1-year Master saves 50% tuition & living cost',
        'roi_wage' => '£11.44 GBP/hr (National Minimum Wage)',
        'roi_qs' => 'Russell Group: Historic universities with elite worldwide reputation',
        'living_cost_local' => '£12,006 GBP',
        'living_cost_inr' => '₹12.5 Lakhs',
        'visa_fee_local' => '£490 GBP',
        'visa_fee_inr' => '₹52,000',
        'weekly_budget_local' => '£200 – £350 GBP',
        'weekly_budget_inr' => 'Covers student halls & local transit',
        'earnings_potential_local' => '£25,000+ GBP',
        'earnings_potential_inr' => 'Estimated annual income if working allowed 20 hrs/week',
        'stayback_bachelors' => '2 Years',
        'stayback_bachelors_stem' => '2 Years',
        'stayback_masters' => '2 Years',
        'stayback_doctoral' => '3 Years',
        'stayback_regional' => 'Russell Group Placement Benefits',
        'upcoming_intakes' => "September (Major Intake) | Deadline: May - June\nJanuary (Secondary Intake) | Deadline: September - October",
        'demand_careers' => "Business Analysts\nCybersecurity Specialists\nRegistered Nurses\nMechanical Engineers",
        'features' => '["1-Year Master\'s Saving","2-Year Graduate Visa","Russell Group Network","No GRE/GMAT Required"]'
    ],
    'canada' => [
        'travel_hours' => 'Approx 14-16 hours',
        'study_options' => "Diploma, Postgraduate Diploma, Bachelor's, Master's",
        'roi_advantage' => 'Post-Graduation Work Permit (PGWP): Up to 3 Years',
        'roi_priority' => 'SDS Stream: Fast-track visa processing with GIC',
        'roi_wage' => '$15.00 - $17.30 CAD/hr (Depending on province)',
        'roi_qs' => 'Top Public Unis: Highly ranked options in Toronto, BC, Montreal',
        'living_cost_local' => '$20,635 CAD',
        'living_cost_inr' => '₹12.6 Lakhs',
        'visa_fee_local' => '$150 CAD',
        'visa_fee_inr' => '₹9,000',
        'weekly_budget_local' => '$300 – $450 CAD',
        'weekly_budget_inr' => 'Covers shared rooms & bus pass',
        'earnings_potential_local' => '$30,000+ CAD',
        'earnings_potential_inr' => 'Covers basic necessities and tuition buffers',
        'stayback_bachelors' => '3 Years',
        'stayback_bachelors_stem' => '3 Years',
        'stayback_masters' => '3 Years',
        'stayback_doctoral' => '3 Years',
        'stayback_regional' => 'Provincial Nominee Program (PNP) pathways',
        'upcoming_intakes' => "September (Fall) | Deadline: Feb - April\nJanuary (Winter) | Deadline: June - August\nMay (Spring) | Deadline: Nov - January",
        'demand_careers' => "Cloud Architects\nConstruction Managers\nRegistered Nurses\nAI Researchers",
        'features' => '["Up to 3-Year PGWP","Express Entry & PR Path","SDS Fast Visa stream","High Quality of Life"]'
    ],
    'germany' => [
        'travel_hours' => 'Approx 8-10 hours (Flight from India)',
        'study_options' => "Free Public Education, Tuition-free Master's, English Taught STEM Courses, MBA, PhD",
        'roi_advantage' => 'Zero Tuition: Virtually free education at world-renowned public universities',
        'roi_priority' => '18-Month Job Seek Route: Guaranteed stay-back search visa for international graduates',
        'roi_wage' => 'Minimum Wage: €12.41 / hr (Among highest student wages in Europe)',
        'roi_qs' => 'TU9 Network: Historic technical universities with stellar global prestige',
        'living_cost_local' => '€11,904 EUR (Blocked Account)',
        'living_cost_inr' => '₹10.8 Lakhs',
        'visa_fee_local' => '€75 EUR',
        'visa_fee_inr' => '₹6,800',
        'weekly_budget_local' => '€150 - €250 EUR',
        'weekly_budget_inr' => 'Covers student hall rent & transport card',
        'earnings_potential_local' => '€14,000+ EUR',
        'earnings_potential_inr' => 'Annual income limit for working 140 full days per year',
        'stayback_bachelors' => '1.5 Years',
        'stayback_bachelors_stem' => '1.5 Years',
        'stayback_masters' => '1.5 Years',
        'stayback_doctoral' => '1.5 Years',
        'stayback_regional' => 'EU Blue Card Eligibility',
        'upcoming_intakes' => "Winter (October Main) | Deadline: July 15\nSummer (April Secondary) | Deadline: January 15",
        'demand_careers' => "Automotive Engineers\nEmbedded Systems Specialists\nData Scientists\nMechanical Engineers",
        'features' => '["Free Public Tuition","1.5-Year Job Seeker Route","TU9 Elite Network","Highest EU Tech Pay"]'
    ],
    'singapore' => [
        'travel_hours' => 'Approx 4-5 hours (Short flight from India)',
        'study_options' => "Bachelor's, Master's, Executive MBA, Advanced Diplomas",
        'roi_advantage' => 'Global Finance Hub: Direct pathways into international banking and tech MNCs',
        'roi_priority' => 'Fast-track Visas: Direct, fast student visa approvals under 3 weeks',
        'roi_wage' => '$10.00 - $15.00 SGD/hr (Varies by internship & campus jobs)',
        'roi_qs' => 'Ivy of Asia: Home to NUS (#8) and NTU (#26) in the World Top 50',
        'living_cost_local' => '$24,000 SGD',
        'living_cost_inr' => '₹14.8 Lakhs',
        'visa_fee_local' => '$120 SGD',
        'visa_fee_inr' => '₹7,500',
        'weekly_budget_local' => '$300 - $450 SGD',
        'weekly_budget_inr' => 'Covers HDB rental, transit & food center meals',
        'earnings_potential_local' => '$20,000+ SGD',
        'earnings_potential_inr' => 'Permitted industrial work attachment earnings',
        'stayback_bachelors' => '1 Year (LTVP)',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Tuition Grant Stay-back Obligations',
        'upcoming_intakes' => "August (Major Intake) | Deadline: Feb - March\nJanuary (Secondary Intake) | Deadline: August - September",
        'demand_careers' => "Investment Bankers\nSoftware Engineers\nSupply Chain Analysts\nBiotech Researchers",
        'features' => '["NUS/NTU Global Elite","Asia\'s Financial Capital","4h Short Flight Time","Highly Safe Environment"]'
    ],
    'ireland' => [
        'travel_hours' => 'Approx 10-12 hours',
        'study_options' => "Bachelor's, Master's, MBA, Higher Diplomas, PhD",
        'roi_advantage' => 'Silicon Docks: Direct access to European HQs of Google, Meta, Apple, Pfizer',
        'roi_priority' => '2-Year Stay Back: Guaranteed Graduate Visa stay-back for all Masters graduates',
        'roi_wage' => 'Minimum Wage: €12.70 / hr',
        'roi_qs' => 'Top 1% Global Unis: Trinity College Dublin, UCD, Galway',
        'living_cost_local' => '€10,000 EUR',
        'living_cost_inr' => '₹9.1 Lakhs',
        'visa_fee_local' => '€60 EUR',
        'visa_fee_inr' => '₹5,400',
        'weekly_budget_local' => '€200 - €350 EUR',
        'weekly_budget_inr' => 'Student apartments and city Luas transit',
        'earnings_potential_local' => '€13,000+ EUR',
        'earnings_potential_inr' => 'Annual student income limit working allowed 20 hrs/week',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '2 Years',
        'stayback_doctoral' => '2 Years',
        'stayback_regional' => 'Regional Bonus +1 Year',
        'upcoming_intakes' => "September (Main Intake) | Deadline: May 31\nJanuary (Secondary) | Deadline: September 30",
        'demand_careers' => "Data Engineers\nPharmaceutical Analysts\nFinancial Accountants\nCyber Security Architects",
        'features' => '["Silicon Docks HQ Jobs","2-Year Masters Stay-back","Native English Speaking","Top 1% Global Universities"]'
    ],
    'newzealand' => [
        'travel_hours' => 'Approx 15-18 hours',
        'study_options' => "Bachelor's, Master's, PG Diplomas, PhD, Pathway Programs",
        'roi_advantage' => '3-Year Post Study Visa: Generous stay-back for degrees & selected qualifications',
        'roi_priority' => 'Student Work: High part-time employment rate in a top-growing economy',
        'roi_wage' => 'Minimum Wage: $23.15 NZD/hr',
        'roi_qs' => '100% Quality: All 8 public universities ranked in global Top 3%',
        'living_cost_local' => '$20,000 NZD',
        'living_cost_inr' => '₹10.2 Lakhs',
        'visa_fee_local' => '$430 NZD',
        'visa_fee_inr' => '₹22,000',
        'weekly_budget_local' => '$350 - $500 NZD',
        'weekly_budget_inr' => 'Covers sharehouse rent, meals & transit',
        'earnings_potential_local' => '$24,000+ NZD',
        'earnings_potential_inr' => 'Part-time student earnings during study semesters',
        'stayback_bachelors' => '3 Years',
        'stayback_bachelors_stem' => '3 Years',
        'stayback_masters' => '3 Years',
        'stayback_doctoral' => '3 Years',
        'stayback_regional' => 'Regional Points toward PR',
        'upcoming_intakes' => "February (Major Intake) | Deadline: October\nJuly (Secondary Intake) | Deadline: March",
        'demand_careers' => "Construction Project Managers\nEnvironmental Engineers\nRegistered Nurses\nCivil Engineers",
        'features' => '["All public Unis in Top 3%","Up to 3-Year Stayback","Peaceful & Secure (#2 Global)","High Part-Time Jobs"]'
    ],
    'france' => [
        'travel_hours' => 'Approx 8-10 hours',
        'study_options' => "Grande École Business Degrees, Master's, MBA, Fashion & Design, Luxury Management",
        'roi_advantage' => 'Alumni Visa: Exclusive 5-year short-stay visa for all Indian postgrads',
        'roi_priority' => 'Grande École Prestige: Prestigious triple-accredited business schools',
        'roi_wage' => 'Minimum Wage: €11.65 / hr',
        'roi_qs' => 'Business Elite: Home to HEC Paris, INSEAD, ESSEC, EDHEC',
        'living_cost_local' => '€8,000 EUR',
        'living_cost_inr' => '₹7.2 Lakhs',
        'visa_fee_local' => '€99 EUR',
        'visa_fee_inr' => '₹9,000',
        'weekly_budget_local' => '€150 - €250 EUR',
        'weekly_budget_inr' => 'Highly subsidized by French CAF housing grants',
        'earnings_potential_local' => '€11,000+ EUR',
        'earnings_potential_inr' => 'Part-time student earnings during study year',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '2 Years',
        'stayback_doctoral' => '2 Years',
        'stayback_regional' => '5-Year Post-Alumni Visa',
        'upcoming_intakes' => "September (Main Intake) | Deadline: May\nFebruary (Spring Intake) | Deadline: October",
        'demand_careers' => "Brand Managers\nFinancial Analysts\nLuxury Marketing Executives\nEmbedded Software Engineers",
        'features' => '["5-Year Alumni Visa","Subsidized Student Housing","Grande École Business Schools","Top Fashion & Luxury Capital"]'
    ],
    'italy' => [
        'travel_hours' => 'Approx 8-10 hours',
        'study_options' => "Bachelor's, English Taught Master's, Art & Fashion, Architecture, Automotive Engineering",
        'roi_advantage' => 'Regional Scholarships: Up to €7,000/yr in grants covering tuition + living',
        'roi_priority' => 'Affordable Public Tuition: Elite programs under €3,000/yr',
        'roi_wage' => 'Average Student Wage: €8.00 - €12.00 / hr',
        'roi_qs' => 'Historical Elite: Bologna (Est. 1088), Politecnico di Milano, Sapienza',
        'living_cost_local' => '€7,000 EUR',
        'living_cost_inr' => '₹6.3 Lakhs',
        'visa_fee_local' => '€50 EUR',
        'visa_fee_inr' => '₹4,500',
        'weekly_budget_local' => '€120 - €200 EUR',
        'weekly_budget_inr' => 'Student apartments, groceries & regional transit',
        'earnings_potential_local' => '€8,000+ EUR',
        'earnings_potential_inr' => 'Part-time student income from local work',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Permesso di Soggiorno conversion',
        'upcoming_intakes' => "September (Primary Main) | Deadline: April - May",
        'demand_careers' => "Industrial Designers\nAutomotive Engineers\nRenewable Energy Consultants\nFashion Coordinators",
        'features' => '["Government & Regional Grants","Extremely Low Tuition Fees","Politecnico Design Elite","Rich Cultural Heritage"]'
    ],
    'sweden' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "Bachelor's, Master's, STEM, PhD",
        'roi_advantage' => 'Innovation Capital: Home of Nobel Prize, Spotify, IKEA, Ericsson',
        'roi_priority' => '1-Year Stayback: orientation search visa to transition to full-time career',
        'roi_wage' => 'Average Wage: SEK 120 - 150 / hr',
        'roi_qs' => 'Research Power: Karolinska Institute, KTH, Chalmers, Lund',
        'living_cost_local' => 'SEK 104,000',
        'living_cost_inr' => '₹8.2 Lakhs',
        'visa_fee_local' => 'SEK 1,500',
        'visa_fee_inr' => '₹12,000',
        'weekly_budget_local' => 'SEK 2,000 - 3,000',
        'weekly_budget_inr' => 'Student housing & local transit',
        'earnings_potential_local' => 'SEK 120,000+',
        'earnings_potential_inr' => 'Part-time jobs in English-speaking friendly sectors',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Fast-track Work Permits',
        'upcoming_intakes' => "August (Main Autumn) | Deadline: January 15",
        'demand_careers' => "Embedded Software Engineers\nTelecom Experts\nRenewable Tech Researchers\nUI/UX Designers",
        'features' => '["Sweden Nobel Research Tech","1-Year orientation stayback","IKEA Spotify Tech HQ","English widely spoken"]'
    ],
    'south-korea' => [
        'travel_hours' => 'Approx 7-9 hours',
        'study_options' => "Bachelor's, English Taught STEM Programs, MBA, Korean Language Pathways, PhD",
        'roi_advantage' => 'Tech Giant Network: Internships & jobs at Samsung, LG, Hyundai',
        'roi_priority' => 'GKS Scholarships: Fully-funded opportunities covering everything',
        'roi_wage' => 'Minimum Wage: ₩9,860 KRW/hr',
        'roi_qs' => 'SKY Universities: Seoul National, KAIST, Korea University',
        'living_cost_local' => '₩12,000,000 KRW',
        'living_cost_inr' => '₹7.4 Lakhs',
        'visa_fee_local' => '$60 USD',
        'visa_fee_inr' => '₹5,000',
        'weekly_budget_local' => '₩250,000 - 400,000 KRW',
        'weekly_budget_inr' => 'Covers student dorms & subway card',
        'earnings_potential_local' => '₩10,000,000+ KRW',
        'earnings_potential_inr' => 'Part-time convenience, tutor & assistant earnings',
        'stayback_bachelors' => '1 Year (D-10)',
        'stayback_bachelors_stem' => '2 Years (STEM-focused D-10)',
        'stayback_masters' => '2 Years',
        'stayback_doctoral' => '2 Years',
        'stayback_regional' => 'Point-system F-2-R pathways',
        'upcoming_intakes' => "March (Primary Intake) | Deadline: Sept - Oct\nSeptember (Secondary Intake) | Deadline: March - April",
        'demand_careers' => "AI & Robotics Researchers\nSemiconductor Engineers\nGame Developers\nGlobal Trade Coordinators",
        'features' => '["Samsung & LG Internships","Fully Funded GKS Scholarships","KAIST & SKY Elite Unis","Futuristic Tech Hub"]'
    ],
    'uae' => [
        'travel_hours' => 'Approx 3-4 hours (Very close to India)',
        'study_options' => "Branch Campuses (Middlesex, Birmingham, Wollongong, Heriot-Watt), Business, Tech, hospitality",
        'roi_advantage' => 'Tax-Free Careers: Earn high-tier, zero tax salaries post-graduation',
        'roi_priority' => 'Close to Home: Low flight costs, fast visa processing in under 15 days',
        'roi_wage' => '$10.00 - $18.00 USD/hr',
        'roi_qs' => 'Branch Quality: Identical curriculum to parent western campuses',
        'living_cost_local' => 'AED 40,000',
        'living_cost_inr' => '₹9.1 Lakhs',
        'visa_fee_local' => 'AED 3,000',
        'visa_fee_inr' => '₹68,000',
        'weekly_budget_local' => 'AED 600 - 1,000',
        'weekly_budget_inr' => 'Student residences & Dubai metro pass',
        'earnings_potential_local' => 'AED 35,000+',
        'earnings_potential_inr' => 'Part-time and hospitality intern earnings potential',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Golden Visa for High Achievers (5-10 Yrs)',
        'upcoming_intakes' => "September (Main Intake) | Deadline: June - July\nJanuary (Secondary) | Deadline: October - November",
        'demand_careers' => "Digital Marketers\nFintech Associates\nLuxury Hotel Managers\nData Engineers",
        'features' => '["Zero Tax-Free Earnings","Global Branch Campuses","3-Hour Short Flight","Fast 15-Day Visas"]'
    ],
    'netherlands' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "Bachelor's, Research Master's, Applied Sciences, MBA",
        'roi_advantage' => 'Orientation Year (Zoekjaar): 1 year search visa to work in any company',
        'roi_priority' => 'High English Proficiency: 95% English speaking native-equivalent population',
        'roi_wage' => 'Average Wage: €13.27 / hr',
        'roi_qs' => 'Research Superstars: TU Delft, Amsterdam, Utrecht',
        'living_cost_local' => '€14,500 EUR',
        'living_cost_inr' => '₹13.1 Lakhs',
        'visa_fee_local' => '€228 EUR',
        'visa_fee_inr' => '₹20,500',
        'weekly_budget_local' => '€250 - €400 EUR',
        'weekly_budget_inr' => 'Student housing, bicycling & supermarkets',
        'earnings_potential_local' => '€12,500+ EUR',
        'earnings_potential_inr' => 'Permitted student part-time jobs',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Highly Skilled Migrant sponsorship',
        'upcoming_intakes' => "September (Main Autumn) | Deadline: Jan - April\nFebruary (Spring Secondary) | Deadline: Sept - October",
        'demand_careers' => "Logistics Managers\nAI Engineers\nCivil & Water Engineers\nFintech Developers",
        'features' => '["Orientation Search Year","TU Delft Global Elite","95% English Speaking","Stable EU Headquarters Hub"]'
    ],
    'switzerland' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "Global Luxury & Hospitality Management, Culinary Arts, Finance & Private Banking, STEM, PhD",
        'roi_advantage' => 'Highest EU Salaries: World\'s leading tier wages and exceptional quality of life',
        'roi_priority' => 'Paid Internships: Mandatory paid internships during luxury study programs',
        'roi_wage' => 'Minimum Internship Wage: CHF 2,212 / mo (Legally regulated)',
        'roi_qs' => 'Hospitality Ivy: Glion, Les Roches, ETH Zurich, EPFL',
        'living_cost_local' => 'CHF 24,000',
        'living_cost_inr' => '₹22.1 Lakhs',
        'visa_fee_local' => 'CHF 88',
        'visa_fee_inr' => '₹8,100',
        'weekly_budget_local' => 'CHF 400 - 600',
        'weekly_budget_inr' => 'Fully integrated campus boarding & Swiss rail pass',
        'earnings_potential_local' => 'CHF 13,000+ (Regulated Internships)',
        'earnings_potential_inr' => 'Covers a massive percentage of overall tuition fees',
        'stayback_bachelors' => '6 Months',
        'stayback_bachelors_stem' => '6 Months',
        'stayback_masters' => '6 Months',
        'stayback_doctoral' => '6 Months',
        'stayback_regional' => 'Specialist Corporate Sponsorship',
        'upcoming_intakes' => "September (Primary) | Deadline: Jan - March\nFebruary (Secondary) | Deadline: July - September",
        'demand_careers' => "Luxury Brand Directors\nCulinary Directors\nWealth Managers\nCERN Researchers",
        'features' => '["Paid Mandatory Internships","Hospitality & Luxury Ivy","ETH Zurich World Rank","Highest Global Salaries"]'
    ],
    'malaysia' => [
        'travel_hours' => 'Approx 4-5 hours',
        'study_options' => "Dual Degrees, Western Branch Campuses (Monash, Nottingham, Curtin), Engineering, Tech",
        'roi_advantage' => 'Affordable Twinning: Get identical UK/Australian degrees at 1/3rd of the tuition fee',
        'roi_priority' => 'Simple Visa: High visa approval rate without rigid financial blocks',
        'roi_wage' => 'Average Student Wage: MYR 6 - 10 / hr',
        'roi_qs' => 'High Quality Branches: Ranked identical to parent western campuses',
        'living_cost_local' => 'MYR 18,000',
        'living_cost_inr' => '₹3.2 Lakhs',
        'visa_fee_local' => 'MYR 1,500',
        'visa_fee_inr' => '₹27,000',
        'weekly_budget_local' => 'MYR 300 - 450',
        'weekly_budget_inr' => 'Student condos, meals & shared transport',
        'earnings_potential_local' => 'MYR 10,000+',
        'earnings_potential_inr' => 'Covers local living buffers',
        'stayback_bachelors' => 'None (Can transition to Employment Pass)',
        'stayback_bachelors_stem' => 'None',
        'stayback_masters' => 'None',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Fast Pass Tech Track EP',
        'upcoming_intakes' => "January | Deadline: Oct\nMay | Deadline: Feb\nSeptember | Deadline: June",
        'demand_careers' => "Mechanical Design Engineers\nIT Consultants\nProcurement Managers\nAgri-Tech Researchers",
        'features' => '["Western Twinning Programs","Very Low Cost of Living","No IELTS for entry","Modern Multinational hub"]'
    ],
    'denmark' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "Applied Sciences, Masters in Engineering, MBA, Environmental Sciences",
        'roi_advantage' => '6-Month Search Visa: orientation job search period post graduation',
        'roi_priority' => 'Happiest Country: Top-tier safety, clean eco-living, and highly respectful work cultures',
        'roi_wage' => 'Average Wage: DKK 120 - 150 / hr',
        'roi_qs' => 'World Leaders: Copenhagen University, DTU',
        'living_cost_local' => 'DKK 80,000',
        'living_cost_inr' => '₹9.6 Lakhs',
        'visa_fee_local' => 'DKK 2,100',
        'visa_fee_inr' => '₹25,000',
        'weekly_budget_local' => 'DKK 1,500 - 2,200',
        'weekly_budget_inr' => 'Student rooms & city cycle paths',
        'earnings_potential_local' => 'DKK 100,000+',
        'earnings_potential_inr' => 'Covers student rent & essential meals',
        'stayback_bachelors' => '6 Months',
        'stayback_bachelors_stem' => '6 Months',
        'stayback_masters' => '6 Months',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'EU green card pathways',
        'upcoming_intakes' => "September (Autumn Main) | Deadline: March 15",
        'demand_careers' => "Wind Energy Engineers\nSoftware Architects\nRegistered Nurses\nEnvironmental Consultants",
        'features' => '["World\'s Happiest Nation","Renewable Wind Energy Leaders","Informal Academic Style","6-Month Job Search"]'
    ],
    'spain' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "Business (ESADE, IESE), Architecture, Tourism, Fashion Design",
        'roi_advantage' => 'Job Search Visa: 1-year residence permit for international graduates',
        'roi_priority' => 'Global Language: Access to the Spanish-speaking world economy',
        'roi_wage' => 'Minimum Wage: €1,134 / mo',
        'roi_qs' => 'Business Power: Top 10 global MBA programs (IESE, ESADE, IE)',
        'living_cost_local' => '€10,000 EUR',
        'living_cost_inr' => '₹9.0 Lakhs',
        'visa_fee_local' => '€80 EUR',
        'visa_fee_inr' => '₹7,200',
        'weekly_budget_local' => '€150 - €250 EUR',
        'weekly_budget_inr' => 'Covers student housing & tapas lifestyle',
        'earnings_potential_local' => '€12,000+',
        'earnings_potential_inr' => 'Part-time student earnings potential',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'EU Work Permit pathways',
        'upcoming_intakes' => "September (Main) | Deadline: May - June",
        'demand_careers' => "Tourism Managers\nArchitects\nRenewable Energy Specialists\nDigital Marketers",
        'features' => '["Top Global MBAs","1-Year Job Search Visa","Affordable EU Living","Spanish Language Benefit"]'
    ],
    'austria' => [
        'travel_hours' => 'Approx 8-10 hours',
        'study_options' => "Engineering, Music & Arts, Business, PhD",
        'roi_advantage' => 'Red-White-Red Card: 12-month search visa for graduates',
        'roi_priority' => 'Innovation Hub: High R&D investment and tech job growth',
        'roi_wage' => 'Minimum Wage: ~€1,500 / mo (Sector dependent)',
        'roi_qs' => 'Historic Quality: University of Vienna, TU Wien',
        'living_cost_local' => '€12,000 EUR',
        'living_cost_inr' => '₹10.8 Lakhs',
        'visa_fee_local' => '€160 EUR',
        'visa_fee_inr' => '₹14,400',
        'weekly_budget_local' => '€200 - €300 EUR',
        'weekly_budget_inr' => 'Student dorms & efficient transit',
        'earnings_potential_local' => '€14,000+',
        'earnings_potential_inr' => 'Student part-time earnings',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Red-White-Red Card eligibility',
        'upcoming_intakes' => "October (Winter) | Deadline: Sept 5",
        'demand_careers' => "Mechanical Engineers\nIT Specialists\nBiotech Researchers\nEnergy Consultants",
        'features' => '["12-Month Red-White-Red Card","Central EU Location","High Quality of Life","Top Engineering Research"]'
    ],
    'finland' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "STEM, Environmental Sciences, Education, Design",
        'roi_advantage' => '2-Year Search Visa: Generous stay-back for all graduates',
        'roi_priority' => 'Education Leader: World-renowned pedagogical approach',
        'roi_wage' => 'Average Wage: €12 - €15 / hr',
        'roi_qs' => 'Global Elite: University of Helsinki, Aalto University',
        'living_cost_local' => '€12,000 EUR',
        'living_cost_inr' => '₹10.8 Lakhs',
        'visa_fee_local' => '€350 EUR',
        'visa_fee_inr' => '₹31,500',
        'weekly_budget_local' => '€200 - €350 EUR',
        'weekly_budget_inr' => 'Student housing & eco-transit',
        'earnings_potential_local' => '€15,000+',
        'earnings_potential_inr' => 'Part-time jobs in tech-friendly sectors',
        'stayback_bachelors' => '2 Years',
        'stayback_bachelors_stem' => '2 Years',
        'stayback_masters' => '2 Years',
        'stayback_doctoral' => '2 Years',
        'stayback_regional' => 'Fast-track to PR',
        'upcoming_intakes' => "August (Main) | Deadline: January",
        'demand_careers' => "Software Engineers\nRenewable Tech Experts\nSpecial Educators\nData Scientists",
        'features' => '["2-Year Job Search Visa","World\'s Best Education","Innovation & Startups","High English Proficiency"]'
    ],
    'hungary' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "Medicine, Engineering, IT, Business",
        'roi_advantage' => 'Stipendium Hungaricum: Massive scholarship opportunities',
        'roi_priority' => 'Schengen Access: Central EU location for travel and jobs',
        'roi_wage' => 'Average Wage: HUF 1,500 - 2,500 / hr',
        'roi_qs' => 'Historic Unis: ELTE, Debrecen, Szeged',
        'living_cost_local' => '€6,000 EUR',
        'living_cost_inr' => '₹5.4 Lakhs',
        'visa_fee_local' => '€60 EUR',
        'visa_fee_inr' => '₹5,400',
        'weekly_budget_local' => '€120 - €200 EUR',
        'weekly_budget_inr' => 'Very affordable student lifestyle',
        'earnings_potential_local' => '€8,000+',
        'earnings_potential_inr' => 'Student job earnings',
        'stayback_bachelors' => '9 Months',
        'stayback_bachelors_stem' => '9 Months',
        'stayback_masters' => '9 Months',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'EU Blue Card options',
        'upcoming_intakes' => "September (Main) | Deadline: Feb - May",
        'demand_careers' => "IT Developers\nMedical Officers\nAutomotive Engineers\nLogistics Experts",
        'features' => '["Low Tuition & Living Costs","Stipendium Scholarships","Historic Medical Schools","Central EU Hub"]'
    ],
    'lithuania' => [
        'travel_hours' => 'Approx 10-12 hours',
        'study_options' => "IT & Fintech, Life Sciences, Engineering",
        'roi_advantage' => 'Fintech Capital: EU leader in digital banking and startups',
        'roi_priority' => '1-Year Search Visa: Orientation year for all graduates',
        'roi_wage' => 'Average Wage: €8 - €12 / hr',
        'roi_qs' => 'Tech Giants: Vilnius University, VGTU',
        'living_cost_local' => '€7,000 EUR',
        'living_cost_inr' => '₹6.3 Lakhs',
        'visa_fee_local' => '€120 EUR',
        'visa_fee_inr' => '₹10,800',
        'weekly_budget_local' => '€150 - €250 EUR',
        'weekly_budget_inr' => 'Fast internet & digital lifestyle',
        'earnings_potential_local' => '€10,000+',
        'earnings_potential_inr' => 'Part-time tech roles',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Startup Visa pathways',
        'upcoming_intakes' => "September (Main) | Deadline: June",
        'demand_careers' => "Fintech Developers\nBiotech Researchers\nCyber Security Experts\nAI Engineers",
        'features' => '["EU Fintech Capital","1-Year Job Search","Modern Digital Infrastructure","Low Cost of Living"]'
    ],
    'cyprus' => [
        'travel_hours' => 'Approx 7-9 hours',
        'study_options' => "Hotel Management, Business, Shipping, IT",
        'roi_advantage' => 'Global Shipping Hub: Major center for maritime and finance',
        'roi_priority' => 'Easy Visa: Straightforward processing for international students',
        'roi_wage' => 'Average Wage: €7 - €10 / hr',
        'roi_qs' => 'Regional Elite: University of Nicosia, UCY',
        'living_cost_local' => '€8,000 EUR',
        'living_cost_inr' => '₹7.2 Lakhs',
        'visa_fee_local' => '€60 EUR',
        'visa_fee_inr' => '₹5,400',
        'weekly_budget_local' => '€150 - €250 EUR',
        'weekly_budget_inr' => 'Island lifestyle & affordable dorms',
        'earnings_potential_local' => '€9,000+',
        'earnings_potential_inr' => 'Hospitality & finance internships',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'EU Work Permit options',
        'upcoming_intakes' => "October | Deadline: August\nFebruary | Deadline: December",
        'demand_careers' => "Shipping Managers\nHotel Directors\nFinancial Analysts\nIT Support",
        'features' => '["Major Maritime Hub","Simple Visa Process","Mediterranean Lifestyle","English Taught Programs"]'
    ],
    'poland' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "Engineering, Medicine, IT, Business",
        'roi_advantage' => 'Fastest Growing EU Economy: Massive demand for skilled talent',
        'roi_priority' => '1-Year Search Visa: Job search period for graduates',
        'roi_wage' => 'Average Wage: PLN 28 - 40 / hr',
        'roi_qs' => 'Historic Elite: Jagiellonian, Warsaw University',
        'living_cost_local' => '€7,000 EUR',
        'living_cost_inr' => '₹6.3 Lakhs',
        'visa_fee_local' => '€80 EUR',
        'visa_fee_inr' => '₹7,200',
        'weekly_budget_local' => '€150 - €250 EUR',
        'weekly_budget_inr' => 'Modern cities & affordable transit',
        'earnings_potential_local' => '€10,000+',
        'earnings_potential_inr' => 'Student part-time income',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Blue Card Eligibility',
        'upcoming_intakes' => "October (Main) | Deadline: July",
        'demand_careers' => "Software Developers\nMechanical Engineers\nLogistics Specialists\nData Analysts",
        'features' => '["Fastest Growing EU Economy","1-Year Job Search","Top Tech Education","Low Living Expenses"]'
    ],
    'czech-republic' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "Engineering, Medicine, Arts, Business",
        'roi_advantage' => 'Central Hub: Headquarter for many global industrial firms',
        'roi_priority' => '9-Month Search Visa: Orientation period for graduates',
        'roi_wage' => 'Average Wage: CZK 150 - 250 / hr',
        'roi_qs' => 'Prestigious History: Charles University (Est. 1348)',
        'living_cost_local' => '€8,000 EUR',
        'living_cost_inr' => '₹7.2 Lakhs',
        'visa_fee_local' => '€100 EUR',
        'visa_fee_inr' => '₹9,000',
        'weekly_budget_local' => '€150 - €250 EUR',
        'weekly_budget_inr' => 'Beautiful historic cities',
        'earnings_potential_local' => '€9,000+',
        'earnings_potential_inr' => 'Part-time jobs in MNCs',
        'stayback_bachelors' => '9 Months',
        'stayback_bachelors_stem' => '9 Months',
        'stayback_masters' => '9 Months',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'EU Work Permit pathways',
        'upcoming_intakes' => "September (Main) | Deadline: April",
        'demand_careers' => "Automotive Engineers\nSoftware Developers\nMedical Doctors\nDesigners",
        'features' => '["Historic Charles University","Central EU Location","Strong Industrial Base","9-Month Job Search"]'
    ],
    'mauritius' => [
        'travel_hours' => 'Approx 6-7 hours',
        'study_options' => "Business, Tourism, IT, Law (UK/French Partnerships)",
        'roi_advantage' => 'Dual Recognition: Degrees from top UK/Australian partners',
        'roi_priority' => 'YEP Program: 1-2 years work permit for graduates',
        'roi_wage' => 'MUR 100 - 200 / hr',
        'roi_qs' => 'Branch Quality: Middlesex, Curtin, Aberystwyth',
        'living_cost_local' => 'MUR 200,000',
        'living_cost_inr' => '₹3.6 Lakhs',
        'visa_fee_local' => '$0 (Included)',
        'visa_fee_inr' => '₹0',
        'weekly_budget_local' => 'MUR 4,000 - 6,000',
        'weekly_budget_inr' => 'Island student resorts & transit',
        'earnings_potential_local' => 'MUR 120,000+',
        'earnings_potential_inr' => 'Internship & hospitality earnings',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '2 Years',
        'stayback_masters' => '2 Years',
        'stayback_doctoral' => '2 Years',
        'stayback_regional' => 'Young Professional Scheme',
        'upcoming_intakes' => "August | Deadline: June\nFebruary | Deadline: December",
        'demand_careers' => "Hotel Managers\nFintech Analysts\nLegal Consultants\nIT Specialists",
        'features' => '["Top UK/Aus Partnerships","1-2 Year Stayback","No Visa Fee","Tropical Safe Haven"]'
    ],
    'japan' => [
        'travel_hours' => 'Approx 7-9 hours',
        'study_options' => "Robotics, AI, Automotive, Japanese Culture",
        'roi_advantage' => 'Innovation Leader: Access to world-leading tech firms',
        'roi_priority' => '1-Year Search Visa: Orientation search period for graduates',
        'roi_wage' => 'Minimum Wage: ¥1,000+ / hr',
        'roi_qs' => 'Global Giants: Tokyo University, Kyoto University',
        'living_cost_local' => '¥1,200,000',
        'living_cost_inr' => '₹6.8 Lakhs',
        'visa_fee_local' => '¥3,000',
        'visa_fee_inr' => '₹1,800',
        'weekly_budget_local' => '¥25,000 - 40,000',
        'weekly_budget_inr' => 'Efficient subway & local meals',
        'earnings_potential_local' => '¥1,000,000+',
        'earnings_potential_inr' => 'Part-time & research assistant earnings',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Highly Skilled Professional points',
        'upcoming_intakes' => "April (Main) | Deadline: Nov\nOctober | Deadline: April",
        'demand_careers' => "AI Engineers\nRobotics Researchers\nAutomotive Designers\nGlobal Business Managers",
        'features' => '["World Leader in Robotics","1-Year Job Search","High Tech Internships","Rich Cultural Experience"]'
    ],
    'vietnam' => [
        'travel_hours' => 'Approx 5-6 hours',
        'study_options' => "Business, IT, Logistics, Design",
        'roi_advantage' => 'Emerging Asian Tiger: Rapidly growing industrial and tech hub',
        'roi_priority' => 'RMIT Vietnam: World-class Australian degrees at Asian costs',
        'roi_wage' => 'VND 50,000 - 100,000 / hr',
        'roi_qs' => 'Branch Excellence: RMIT, Swinburne, BUV',
        'living_cost_local' => 'VND 150,000,000',
        'living_cost_inr' => '₹5.0 Lakhs',
        'visa_fee_local' => '$135 USD',
        'visa_fee_inr' => '₹11,200',
        'weekly_budget_local' => 'VND 3,000,000',
        'weekly_budget_inr' => 'Affordable living & street food',
        'earnings_potential_local' => 'VND 80,000,000+',
        'earnings_potential_inr' => 'Student internships in MNCs',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Work Permit pathways',
        'upcoming_intakes' => "October | Deadline: August\nFebruary | Deadline: December",
        'demand_careers' => "Logistics Managers\nSoftware Developers\nSupply Chain Analysts\nDesigners",
        'features' => '["Emerging Asian Tiger Hub","Top Australian Branch Unis","Very Low Living Cost","Fast Growing Economy"]'
    ],
    'malta' => [
        'travel_hours' => 'Approx 10-12 hours',
        'study_options' => "IT, Gaming & Fintech, Business, Health",
        'roi_advantage' => 'Gaming Hub: World center for iGaming and blockchain',
        'roi_priority' => '9-Month Search Visa: Job search period for graduates',
        'roi_wage' => 'Minimum Wage: €9.25 / hr',
        'roi_qs' => 'Quality Standards: University of Malta, Middlesex Malta',
        'living_cost_local' => '€9,000 EUR',
        'living_cost_inr' => '₹8.1 Lakhs',
        'visa_fee_local' => '€100 EUR',
        'visa_fee_inr' => '₹9,000',
        'weekly_budget_local' => '€180 - €280 EUR',
        'weekly_budget_inr' => 'English speaking EU island',
        'earnings_potential_local' => '€11,000+',
        'earnings_potential_inr' => 'Gaming & Fintech internships',
        'stayback_bachelors' => '9 Months',
        'stayback_bachelors_stem' => '9 Months',
        'stayback_masters' => '9 Months',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'EU Work Permit pathways',
        'upcoming_intakes' => "October (Main) | Deadline: August",
        'demand_careers' => "Gaming Developers\nFintech Specialists\nNurses\nBusiness Analysts",
        'features' => '["Global iGaming Capital","English Speaking EU","9-Month Job Search","Mediterranean Tech Hub"]'
    ],
    'china' => [
        'travel_hours' => 'Approx 6-8 hours',
        'study_options' => "Engineering, Medicine (MBBS), Business, AI",
        'roi_advantage' => 'Global Giant: World-leading infrastructure and tech labs',
        'roi_priority' => '1-2 Year Stayback: Work search and internship opportunities',
        'roi_wage' => 'CNY 30 - 60 / hr',
        'roi_qs' => 'Top 50 Global: Tsinghua, Peking, Fudan',
        'living_cost_local' => 'CNY 40,000',
        'living_cost_inr' => '₹4.6 Lakhs',
        'visa_fee_local' => '$100 USD',
        'visa_fee_inr' => '₹8,300',
        'weekly_budget_local' => 'CNY 800 - 1,200',
        'weekly_budget_inr' => 'Modern campuses & fast transit',
        'earnings_potential_local' => 'CNY 30,000+',
        'earnings_potential_inr' => 'Research & teaching assistant roles',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '2 Years',
        'stayback_masters' => '2 Years',
        'stayback_doctoral' => '2 Years',
        'stayback_regional' => 'Z-Visa pathways for grads',
        'upcoming_intakes' => "September (Main) | Deadline: April",
        'demand_careers' => "AI Researchers\nCivil Engineers\nGlobal Trade Managers\nBio-Scientists",
        'features' => '["World-Class Infrastructure","Top 50 Global Unis","Massive Tech Research","Low Living Expenses"]'
    ],
    'belgium' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "International Relations, Engineering, Business, MBA",
        'roi_advantage' => 'Heart of Europe: HQ for EU, NATO and global MNCs',
        'roi_priority' => '1-Year Search Visa: Orientation search period for graduates',
        'roi_wage' => 'Average Wage: €12 - €15 / hr',
        'roi_qs' => 'Research Power: KU Leuven (#45), Ghent University',
        'living_cost_local' => '€11,000 EUR',
        'living_cost_inr' => '₹9.9 Lakhs',
        'visa_fee_local' => '€200 EUR',
        'visa_fee_inr' => '₹18,000',
        'weekly_budget_local' => '€200 - €350 EUR',
        'weekly_budget_inr' => 'Multicultural cities & rail access',
        'earnings_potential_local' => '€13,000+',
        'earnings_potential_inr' => 'Internships in EU & NGOs',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Work Permit sponsorship',
        'upcoming_intakes' => "September (Main) | Deadline: March",
        'demand_careers' => "Policy Analysts\nSoftware Engineers\nSupply Chain Managers\nFinancial Experts",
        'features' => '["Heart of EU & NATO","1-Year Job Search","KU Leuven Global Elite","Top Multicultural Hub"]'
    ],
    'bulgaria' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "EU Medical Degrees (MD), Dentistry, Pharmacy, Software Engineering",
        'roi_advantage' => 'EU Recognition: Full licensing and employment rights across the entire European Union',
        'roi_priority' => 'Budget Gateway: Lowest tuition fees and cost of living in the EU',
        'roi_wage' => 'Average Student Wage: BGN 5 - 8 / hr',
        'roi_qs' => 'Niche Excellence: Sofia Medical University, Technical University',
        'living_cost_local' => 'BGN 12,000',
        'living_cost_inr' => '₹5.5 Lakhs',
        'visa_fee_local' => 'BGN 200',
        'visa_fee_inr' => '₹9,000',
        'weekly_budget_local' => 'BGN 200 - 300',
        'weekly_budget_inr' => 'Student housing & local tram cards',
        'earnings_potential_local' => 'BGN 6,000+',
        'earnings_potential_inr' => 'Local student support earnings',
        'stayback_bachelors' => 'None (Direct EU transition)',
        'stayback_bachelors_stem' => 'None',
        'stayback_masters' => 'None',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'European Blue Card options',
        'upcoming_intakes' => "October (Primary Main) | Deadline: July - August",
        'demand_careers' => "Medical Doctors\nDentists\nCloud Support Engineers\nPharmacists",
        'features' => '["Lowest EU Tuition Costs","EU Medical Degree License","Extremely Cheap Living","Sofia Tech Hub Growth"]'
    ],
    'russia' => [
        'travel_hours' => 'Approx 6-8 hours',
        'study_options' => "General Medicine (MD/MBBS), Aeronautical Engineering, Space Research, Nuclear Physics",
        'roi_advantage' => 'Highly Subsidized: Massive medical education support from the federal government',
        'roi_priority' => 'No Entrance Barrier: Simple visa pathways with zero restrictive entrance blocks',
        'roi_wage' => 'Average Student Wage: RUB 150 - 250 / hr',
        'roi_qs' => 'Historic Giants: Lomonosov Moscow State, Saint Petersburg University',
        'living_cost_local' => 'RUB 360,000',
        'living_cost_inr' => '₹3.3 Lakhs',
        'visa_fee_local' => '$100 USD',
        'visa_fee_inr' => '₹8,300',
        'weekly_budget_local' => 'RUB 7,000 - 10,000',
        'weekly_budget_inr' => 'Covers student hostels & local transit',
        'earnings_potential_local' => 'RUB 180,000+',
        'earnings_potential_inr' => 'Covers basic student meals and pocket money',
        'stayback_bachelors' => '6 Months',
        'stayback_bachelors_stem' => '6 Months',
        'stayback_masters' => '6 Months',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'RVP student temporary residence permits',
        'upcoming_intakes' => "September (Main Autumn) | Deadline: June 15",
        'demand_careers' => "Medical Officers\nAircraft Design Engineers\nNuclear Tech Specialists\nSoftware Developers",
        'features' => '["Fully Subsidized Medicine","Historic Space & Science Tech","Very Low Living Expenses","Direct Clinical Internships"]'
    ],
    'georgia' => [
        'travel_hours' => 'Approx 7-9 hours',
        'study_options' => "Medicine (EU Pattern), Engineering, Business",
        'roi_advantage' => 'Medical Gateway: High quality medical schools with EU pattern',
        'roi_priority' => 'Low Living Costs: Most affordable EU-standard living',
        'roi_wage' => 'GEL 5 - 10 / hr',
        'roi_qs' => 'Regional Giants: TSU, Caucasus University',
        'living_cost_local' => 'GEL 10,000',
        'living_cost_inr' => '₹3.1 Lakhs',
        'visa_fee_local' => 'GEL 100',
        'visa_fee_inr' => '₹3,100',
        'weekly_budget_local' => 'GEL 200 - 350',
        'weekly_budget_inr' => 'Very affordable student lifestyle',
        'earnings_potential_local' => 'GEL 6,000+',
        'earnings_potential_inr' => 'Local student job earnings',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Residence Permit options',
        'upcoming_intakes' => "October | Deadline: August\nMarch | Deadline: January",
        'demand_careers' => "Medical Practitioners\nConstruction Engineers\nIT Support\nBusiness Analysts",
        'features' => '["EU Pattern Medical Degree","Extremely Affordable Living","Safe & Friendly Culture","No Entrance Barriers"]'
    ],
    'croatia' => [
        'travel_hours' => 'Approx 10-12 hours',
        'study_options' => "Hospitality, IT, Business, Maritime Studies",
        'roi_advantage' => 'Tourism Leader: World center for hospitality and maritime',
        'roi_priority' => '1-Year Search Visa: Orientation period for graduates',
        'roi_wage' => 'Average Wage: €7 - €10 / hr',
        'roi_qs' => 'Regional Elite: University of Zagreb',
        'living_cost_local' => '€8,000 EUR',
        'living_cost_inr' => '₹7.2 Lakhs',
        'visa_fee_local' => '€80 EUR',
        'visa_fee_inr' => '₹7,200',
        'weekly_budget_local' => '€150 - €250 EUR',
        'weekly_budget_inr' => 'Beautiful Adriatic lifestyle',
        'earnings_potential_local' => '€9,000+',
        'earnings_potential_inr' => 'Hospitality & IT internships',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'EU Work Permit pathways',
        'upcoming_intakes' => "October | Deadline: August",
        'demand_careers' => "Hotel Managers\nSoftware Developers\nMaritime Engineers\nTourism Analysts",
        'features' => '["World Tourism Leader","1-Year Job Search","Beautiful Adriatic Setting","English Taught Programs"]'
    ],
    'latvia' => [
        'travel_hours' => 'Approx 10-12 hours',
        'study_options' => "Engineering, IT, Business, Medicine",
        'roi_advantage' => 'Baltic Tech Hub: Rapidly growing digital and tech ecosystem',
        'roi_priority' => '1-Year Search Visa: Job search period for graduates',
        'roi_wage' => 'Average Wage: €6 - €10 / hr',
        'roi_qs' => 'Regional Tech: Riga Technical University',
        'living_cost_local' => '€7,000 EUR',
        'living_cost_inr' => '₹6.3 Lakhs',
        'visa_fee_local' => '€60 EUR',
        'visa_fee_inr' => '₹5,400',
        'weekly_budget_local' => '€150 - €250 EUR',
        'weekly_budget_inr' => 'Modern digital cities',
        'earnings_potential_local' => '€8,000+',
        'earnings_potential_inr' => 'IT & Engineering internships',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Blue Card Eligibility',
        'upcoming_intakes' => "September | Deadline: June",
        'demand_careers' => "Software Developers\nMechanical Engineers\nBiotech Analysts\nFinancial Experts",
        'features' => '["Innovative Baltic Tech Hub","1-Year Job Search","Low Cost of Living","EU Standard Education"]'
    ],
    'luxembourg' => [
        'travel_hours' => 'Approx 10-12 hours',
        'study_options' => "Finance & Banking, Law, Engineering, PhD",
        'roi_advantage' => 'Highest Global Salaries: Leading tier for finance and tech',
        'roi_priority' => '9-Month Search Visa: Job search period for graduates',
        'roi_wage' => 'Minimum Wage: €14.50+ / hr',
        'roi_qs' => 'Elite Ranking: University of Luxembourg',
        'living_cost_local' => '€15,000 EUR',
        'living_cost_inr' => '₹13.5 Lakhs',
        'visa_fee_local' => '€50 EUR',
        'visa_fee_inr' => '₹4,500',
        'weekly_budget_local' => '€300 - €450 EUR',
        'weekly_budget_inr' => 'Free public transport nationwide',
        'earnings_potential_local' => '€16,000+',
        'earnings_potential_inr' => 'Finance & Legal internships',
        'stayback_bachelors' => '9 Months',
        'stayback_bachelors_stem' => '9 Months',
        'stayback_masters' => '9 Months',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Work Permit sponsorship',
        'upcoming_intakes' => "September | Deadline: June",
        'demand_careers' => "Wealth Managers\nLegal Analysts\nData Scientists\nFinancial Auditors",
        'features' => '["Highest Global Salaries","Free Public Transport","Global Finance Hub","9-Month Job Search"]'
    ],
    'greece' => [
        'travel_hours' => 'Approx 9-11 hours',
        'study_options' => "Maritime Studies, Business, History & Arts",
        'roi_advantage' => 'Maritime World Leader: Center for global shipping',
        'roi_priority' => '1-Year Search Visa: Orientation period for graduates',
        'roi_wage' => 'Average Wage: €7 - €10 / hr',
        'roi_qs' => 'Historic Elite: National & Kapodistrian Uni',
        'living_cost_local' => '€8,000 EUR',
        'living_cost_inr' => '₹7.2 Lakhs',
        'visa_fee_local' => '€90 EUR',
        'visa_fee_inr' => '₹8,100',
        'weekly_budget_local' => '€150 - €250 EUR',
        'weekly_budget_inr' => 'Rich culture & island access',
        'earnings_potential_local' => '€9,000+',
        'earnings_potential_inr' => 'Shipping & tourism internships',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'EU Work Permit options',
        'upcoming_intakes' => "October | Deadline: August",
        'demand_careers' => "Shipping Operations\nLogistics Managers\nArchaeologists\nHotel Directors",
        'features' => '["Maritime World Leader","Historic Academic Roots","1-Year Job Search","Affordable EU Living"]'
    ],
    'india' => [
        'travel_hours' => 'Local',
        'study_options' => "IIT/IIM Elite, Engineering, Medicine, Management",
        'roi_advantage' => 'Fastest Growing Economy: Massive domestic career growth',
        'roi_priority' => 'World-Class Research: IITs and IIMs global prestige',
        'roi_wage' => 'Varies by Sector',
        'roi_qs' => 'Top Institutes: IIT Bombay, IIT Delhi, IISc',
        'living_cost_local' => '₹3,00,000',
        'living_cost_inr' => '₹3.0 Lakhs',
        'visa_fee_local' => 'N/A',
        'visa_fee_inr' => 'N/A',
        'weekly_budget_local' => '₹5,000 - ₹10,000',
        'weekly_budget_inr' => 'Covers local hostels & meals',
        'earnings_potential_local' => 'Varies',
        'earnings_potential_inr' => 'Campus placement opportunities',
        'stayback_bachelors' => 'N/A',
        'stayback_bachelors_stem' => 'N/A',
        'stayback_masters' => 'N/A',
        'stayback_doctoral' => 'N/A',
        'stayback_regional' => 'Global Talent Hub',
        'upcoming_intakes' => "July (Main) | Deadline: April",
        'demand_careers' => "Software Engineers\nData Scientists\nBusiness Analysts\nHealthcare Experts",
        'features' => '["Fastest Growing Economy","IIT/IIM Global Elite","Massive Tech Growth","Low Education Cost"]'
    ],
    'kazakhstan' => [
        'travel_hours' => 'Approx 6-8 hours',
        'study_options' => "Medicine, STEM, Oil & Gas Engineering",
        'roi_advantage' => 'Energy Hub: Leader in oil, gas and minerals research',
        'roi_priority' => '1-Year Search Visa: Job search period for graduates',
        'roi_wage' => 'Average Wage: KZT 1,000 - 2,000 / hr',
        'roi_qs' => 'Elite Ranking: Nazarbayev University',
        'living_cost_local' => 'KZT 2,000,000',
        'living_cost_inr' => '₹3.6 Lakhs',
        'visa_fee_local' => '$80 USD',
        'visa_fee_inr' => '₹6,600',
        'weekly_budget_local' => 'KZT 40,000 - 60,000',
        'weekly_budget_inr' => 'Modern cities & low costs',
        'earnings_potential_local' => 'KZT 1,200,000+',
        'earnings_potential_inr' => 'Oil, Gas & Tech internships',
        'stayback_bachelors' => '1 Year',
        'stayback_bachelors_stem' => '1 Year',
        'stayback_masters' => '1 Year',
        'stayback_doctoral' => '1 Year',
        'stayback_regional' => 'Work Permit pathways',
        'upcoming_intakes' => "September | Deadline: June",
        'demand_careers' => "Petroleum Engineers\nMedical Officers\nIT Specialists\nGeologists",
        'features' => '["Central Asian Tech Leader","Top Oil & Gas Research","1-Year Job Search","Very Affordable Living"]'
    ],
    'philippines' => [
        'travel_hours' => 'Approx 6-7 hours',
        'study_options' => "MD / MBBS (American Medical Pattern), English Taught Allied Health Sciences",
        'roi_advantage' => 'US Medical Gateway: Designed explicitly to succeed in USMLE, FMGE & clinical licensing',
        'roi_priority' => 'English Native Classrooms: 100% English medium of study in a highly warm tropical climate',
        'roi_wage' => 'Not recommended (Students focus 100% on medical clinical studies)',
        'roi_qs' => 'Medical Giants: University of Santo Tomas, University of the Philippines',
        'living_cost_local' => '$3,600 USD',
        'living_cost_inr' => '₹3.0 Lakhs',
        'visa_fee_local' => '$140 USD',
        'visa_fee_inr' => '₹11,500',
        'weekly_budget_local' => '$60 - $100 USD',
        'weekly_budget_inr' => 'Shared student condos & clinical meals',
        'earnings_potential_local' => 'Focus on Medical Studies',
        'earnings_potential_inr' => 'No part-time working recommended to clear clinical exams',
        'stayback_bachelors' => 'None (Graduates return or fly to US/UK clinical posts)',
        'stayback_bachelors_stem' => 'None',
        'stayback_masters' => 'None',
        'stayback_doctoral' => 'None',
        'stayback_regional' => 'US Hospital clinical training attachments',
        'upcoming_intakes' => "June (Primary Medical) | Deadline: March - April\nNovember (Secondary Medical) | Deadline: August - September",
        'demand_careers' => "General Medical Practitioners\nClinical Consultants\nSurgical Registrars\nRegistered Nurses",
        'features' => '["American Pattern MD Degree","High FMGE/NEXT Passing Rate","100% English Medium Study","Tropical & Friendly Culture"]'
    ]
];

try {
    foreach ($allCountriesData as $slug => $data) {
        // Find existing country ID
        $stmt = $pdo->prepare("SELECT id FROM `countries` WHERE `slug` = :slug");
        $stmt->execute(['slug' => $slug]);
        $country = $stmt->fetch();
        
        if ($country) {
            $countryId = $country['id'];
            
            // Perform update
            $updateSql = "UPDATE `countries` SET 
                `travel_hours` = :travel_hours,
                `study_options` = :study_options,
                `roi_advantage` = :roi_advantage,
                `roi_priority` = :roi_priority,
                `roi_wage` = :roi_wage,
                `roi_qs` = :roi_qs,
                `living_cost_local` = :living_cost_local,
                `living_cost_inr` = :living_cost_inr,
                `visa_fee_local` = :visa_fee_local,
                `visa_fee_inr` = :visa_fee_inr,
                `weekly_budget_local` = :weekly_budget_local,
                `weekly_budget_inr` = :weekly_budget_inr,
                `earnings_potential_local` = :earnings_potential_local,
                `earnings_potential_inr` = :earnings_potential_inr,
                `stayback_bachelors` = :stayback_bachelors,
                `stayback_bachelors_stem` = :stayback_bachelors_stem,
                `stayback_masters` = :stayback_masters,
                `stayback_doctoral` = :stayback_doctoral,
                `stayback_regional` = :stayback_regional,
                `upcoming_intakes` = :upcoming_intakes,
                `demand_careers` = :demand_careers,
                `features` = :features,
                `image_url` = :image_url,
                `is_active` = 1
                WHERE `id` = :id";
            
            $updateParams = array_merge($data, [
                'id' => $countryId,
                'image_url' => "assets/images/countries/{$slug}.jpg"
            ]);
            $updateStmt = $pdo->prepare($updateSql);
            $updateStmt->execute($updateParams);
            
            echo "[SUCCESS] Seeded 2026 details for existing country: '$slug' (ID: $countryId)\n";
        } else {
            // Generate clean flag & name
            $name = ucfirst($slug);
            if ($slug === 'usa') $name = 'USA';
            if ($slug === 'uk') $name = 'UK';
            if ($slug === 'newzealand') $name = 'New Zealand';
            if ($slug === 'south-korea') $name = 'South Korea';
            if ($slug === 'uae') $name = 'UAE';
            if ($slug === 'czech-republic') $name = 'Czech Republic';
            
            $flag = '🌐';
            if ($slug === 'usa') $flag = '🇺🇸';
            if ($slug === 'uk') $flag = '🇬🇧';
            if ($slug === 'canada') $flag = '🇨🇦';
            if ($slug === 'australia') $flag = '🇦🇺';
            if ($slug === 'germany') $flag = '🇩🇪';
            if ($slug === 'singapore') $flag = '🇸🇬';
            if ($slug === 'ireland') $flag = '🇮🇪';
            if ($slug === 'newzealand') $flag = '🇳🇿';
            if ($slug === 'france') $flag = '🇫🇷';
            if ($slug === 'italy') $flag = '🇮🇹';
            if ($slug === 'sweden') $flag = '🇸🇪';
            if ($slug === 'south-korea') $flag = '🇰🇷';
            if ($slug === 'uae') $flag = '🇦🇪';
            if ($slug === 'netherlands') $flag = '🇳🇱';
            if ($slug === 'switzerland') $flag = '🇨🇭';
            if ($slug === 'malaysia') $flag = '🇲🇾';
            if ($slug === 'denmark') $flag = '🇩🇰';
            if ($slug === 'bulgaria') $flag = '🇧🇬';
            if ($slug === 'russia') $flag = '🇷🇺';
            if ($slug === 'philippines') $flag = '🇵🇭';
            if ($slug === 'spain') $flag = '🇪🇸';
            if ($slug === 'austria') $flag = '🇦🇹';
            if ($slug === 'finland') $flag = '🇫🇮';
            if ($slug === 'hungary') $flag = '🇭🇺';
            if ($slug === 'lithuania') $flag = '🇱🇹';
            if ($slug === 'cyprus') $flag = '🇨🇾';
            if ($slug === 'poland') $flag = '🇵🇱';
            if ($slug === 'czech-republic') $flag = '🇨🇿';
            if ($slug === 'mauritius') $flag = '🇲🇺';
            if ($slug === 'japan') $flag = '🇯🇵';
            if ($slug === 'vietnam') $flag = '🇻🇳';
            if ($slug === 'malta') $flag = '🇲🇹';
            if ($slug === 'china') $flag = '🇨🇳';
            if ($slug === 'belgium') $flag = '🇧🇪';
            if ($slug === 'georgia') $flag = '🇬🇪';
            if ($slug === 'croatia') $flag = '🇭🇷';
            if ($slug === 'latvia') $flag = '🇱🇻';
            if ($slug === 'luxembourg') $flag = '🇱🇺';
            if ($slug === 'greece') $flag = '🇬🇷';
            if ($slug === 'india') $flag = '🇮🇳';
            if ($slug === 'kazakhstan') $flag = '🇰🇿';

            // Insert brand new
            $insertSql = "INSERT INTO `countries` (
                `slug`, `name`, `flag`, `description`, `travel_hours`, `study_options`, 
                `roi_advantage`, `roi_priority`, `roi_wage`, `roi_qs`, 
                `living_cost_local`, `living_cost_inr`, `visa_fee_local`, `visa_fee_inr`, 
                `weekly_budget_local`, `weekly_budget_inr`, `earnings_potential_local`, `earnings_potential_inr`, 
                `stayback_bachelors`, `stayback_bachelors_stem`, `stayback_masters`, `stayback_doctoral`, `stayback_regional`, 
                `upcoming_intakes`, `demand_careers`, `features`, `image_url`, `is_active`
            ) VALUES (
                :slug, :name, :flag, :description, :travel_hours, :study_options, 
                :roi_advantage, :roi_priority, :roi_wage, :roi_qs, 
                :living_cost_local, :living_cost_inr, :visa_fee_local, :visa_fee_inr, 
                :weekly_budget_local, :weekly_budget_inr, :earnings_potential_local, :earnings_potential_inr, 
                :stayback_bachelors, :stayback_bachelors_stem, :stayback_masters, :stayback_doctoral, :stayback_regional, 
                :upcoming_intakes, :demand_careers, :features, :image_url, 1
            )";
            
            $insertParams = array_merge($data, [
                'slug' => $slug,
                'name' => $name,
                'flag' => $flag,
                'image_url' => "assets/images/countries/{$slug}.jpg",
                'description' => "Explore premium 2026 pathways for study, stay-back, and career success in $name."
            ]);
            
            $insertStmt = $pdo->prepare($insertSql);
            $insertStmt->execute($insertParams);
            $countryId = $pdo->lastInsertId();
            echo "[SUCCESS] Created and seeded new country: '$slug' (ID: $countryId)\n";
        }
    }

    echo "\n=== ALL 39+ COUNTRIES SEEDED AND SYNCHRONIZED SUCCESSFULLY ===\n";

} catch (PDOException $e) {
    echo "\n[ERROR] Seeding Failed: " . $e->getMessage() . "\n";
}
echo "</pre>";
